# Colores oscuros
COLOR_DE_FONDO_DARK = "#1a1b28"
COLOR_DE_TEXTO_DARK = "white"
COLOR_BOTONES_ESPECIALES_DARK = "#52c9dc"
COLOR_BOTONES_DARK = "#1e2435"
COLOR_CAJA_TEXTO_DARK = "#1a1b28"

# Colores claros
COLOR_DE_FONDO_LIGHT = "#ffffff"
COLOR_DE_TEXTO_LIGHT = "black"
COLOR_BOTONES_ESPECIALES_LIGHT = "#52c9dc"
COLOR_BOTONES_LIGHT = "#f2f8fc"
COLOR_CAJA_TEXTO_LIGHT = "#ffffff"